---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: .*
    patch: |-
      - op: add
        path: /metadata/labels
        value: { l2-overlay-infra: "", k8s.ovn.org/primary-user-defined-network: ""}

  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/devices/interfaces/0
        value: {
          "name": "default",
          "binding": {"name": "l2bridge"},
          "model": "virtio"
        }