apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-autofs
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/dlbewley/demo-autofs'
      targetRevision: feature/cudn
      path: argo-apps/demo-autofs
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
