---
# see /automount/machineconfig.bu
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-automount
  name: 99-worker-automount-sssd-config
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            compression: gzip
            source: data:;base64,H4sIAAAAAAAC/4ySQUs7MRDF7/kUAz30/4dte1YIKHoRFDx4KyVMkqkbzSZLJlntxc8u6RZt2Ra8JJl5v3l5gayZ2W4EUxqcIQYJgbmBHrsGsOS4ZWFjhy5U6fH+9lnMLOnyqjwN5EHClRDrkVhVeSOcVX2Kg7OUQIK32AssuZ00Tdsj8zk2bqftuqiS3KG+Xq3qtvSol5o+PO2WgfJIMWEyrdLIBBKskR51Y40cuXr6QQ+XnU7EImu/iyXk5tL4bJ1izDfGOwoZvjazfazRCBbtvoLFJyz0n/xg/i/qNzL5ziPzL/+E/f/5SdYOezWiylQWJBzTJyyFnHYX6YltwG58/xmTd9qBBBPOSAP6QsfGD2EbU4fZxSAMmpaUSWQpZIe+JnhJhabf6DsAAP//58MH5IoCAAA=
          mode: 0600
          path: /etc/sssd/sssd.conf
          user:
            name: root
    systemd:
      units:
        - enabled: true
          name: sssd.service

---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-automount
  name: 99-worker-automount-autofs-service
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - enabled: true
          name: autofs.service

---
# needed? probably not for this use case...
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-automount-nfs-homedir-setsebool
  labels:
    machineconfiguration.openshift.io/role: worker-automount
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - name: setsebool-nfs-home.service
          enabled: true
          contents: |
            [Unit]
            Description=Set SELinux boolean use_nfs_home_dirs
            After=network.target

            [Service]
            Type=oneshot
            ExecStart=/usr/sbin/setsebool -P use_nfs_home_dirs 1

            [Install]
            WantedBy=multi-user.target