apiVersion: machineconfiguration.openshift.io/v1alpha1
kind: MachineOSConfig
metadata:
  name: worker-automount
spec:
  machineConfigPool:
    name: worker-automount
  buildInputs:
    containerFile: 
    - containerfileArch: noarch
      content: |-
        FROM configs AS final
        LABEL layered-source="https://github.com/dbewley/demo-autofs"
        RUN dnf install -y \
          autofs \
          openldap-clients \
          && dnf clean all \
          && ostree container commit
    imageBuilder: 
      imageBuilderType: PodImageBuilder
    # MCO uses to pull the base operating system image from the registry
    # this will be obviated in OCP 4.19
    baseImagePullSecret: 
      # a copy of openshift-config:secret/pull-secret
      name: pull-secret
    renderedImagePushspec: image-registry.openshift-image-registry.svc:5000/openshift/os-image:latest 
    renderedImagePushSecret: 
      # a copy of openshift-config:secret/builder-dockercfg-5dsjz
      name: push-secret
  buildOutputs: 
    # nodes need in order to pull the newly built custom layered image
    currentImagePullSecret:
      name: push-secret