apiVersion: machineconfiguration.openshift.io/v1
kind: MachineOSConfig
metadata:
  name: worker-automount
spec:
  machineConfigPool:
    name: worker-automount
  containerFile: 
  - content: |-
      FROM configs AS final
      LABEL layered-source="https://github.com/dbewley/demo-autofs"
      RUN dnf install -y \
        autofs \
        libsss_autofs \
        openldap-clients \
        && dnf clean all \
        && ostree container commit
  imageBuilder: 
    imageBuilderType: Job
  baseImagePullSecret: 
    # baseImagePullSecret is the secret used to pull the base image.
    name: pull-and-push-secret
  renderedImagePushSecret: 
    # renderedImagePushSecret is the secret used to connect to a user registry.
    name: push-secret
  renderedImagePushSpec: image-registry.openshift-image-registry.svc:5000/openshift-machine-config-operator/os-image:latest 