apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  annotation:
    description: Worker nodes with automount enabled
  labels:
    pools.operator.machineconfiguration.openshift.io/worker-automount: ""
  name: worker-automount
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - worker-automount
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-automount: ""
  paused: true
