---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-ldap

labels:
  - includeSelectors: true
    pairs:
      demo: ldap
      app.kubernetes.io/instance: demo-autofs-ldap

components:
  - ../../components/argocd-vm-management

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ldap-ldif
    files:
      - scripts/autofs.ldif
      - scripts/automount.ldif
      - scripts/base.ldif
      - scripts/ldap-load.sh
      - scripts/modify-suffix.ldif
      - scripts/set-rootdn.ldif
      - scripts/users.ldif

secretGenerator:
  - name: cloudinitdisk-ldap
    files:
      - scripts/userData

resources:
  - namespace.yaml
  - multinetworkpolicy.yaml
  - virtualmachine.yaml

patches:
  # i wish to manually handle updates to this secret for now
  - target:
      kind: Secret
      name: cloudinitdisk-ldap
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: Skip
          argocd.argoproj.io/sync-options: Prune=false

  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/devices/interfaces/0
        value: {
          "name": "nic-1924",
          "bridge": {},
          "model": "virtio"
        }
      - op: replace
        path: /spec/template/spec/networks/0
        value: {
          "name": "nic-1924",
          "multus": {
            "networkName": "localnet-1924"
          }
        }
      - op: replace
        path: /spec/runStrategy
        value: Always

      # add volumes for secret and configmap
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud
        value: {
          "secretRef": {
            "name": "cloudinitdisk-ldap"
          }
        }
      - op: add
        path: /spec/template/spec/volumes/-
        value: {
          "name": "ldap-ldif",
          "configMap": {
            "name": "ldap-ldif"
          }
        }
      - op: add
        path: /spec/template/spec/domain/devices/disks/-
        value: {
          "name": "ldap-ldif",
          "serial": "ldap-ldif",
          "disk": {
            "bus": "virtio"
          }
        }