---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-client

labels:
  - includeSelectors: true
    pairs:
      demo: client
      app.kubernetes.io/instance: demo-autofs-client

components:
  - ../../components/argocd-vm-management

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sssd-conf
    files:
      - scripts/sssd.conf
      - scripts/homedir.conf

secretGenerator:
  - name: cloudinitdisk-client-sample
    files:
      - scripts/userData

resources:
  - namespace.yaml
  - externalsecret.yaml
  - virtualmachine.yaml

patches:
  # i wish to manually handle updates to this secret for now
  - target:
      kind: Secret
      name: cloudinitdisk-client
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: Skip
          argocd.argoproj.io/sync-options: Prune=false

  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/devices/interfaces/0
        value: {
          "name": "nic-1924",
          "bridge": {},
          "model": "virtio"
        }
      - op: replace
        path: /spec/template/spec/networks/0
        value: {
          "name": "nic-1924",
          "multus": {
            "networkName": "localnet-1924-dhcp"
          }
        }

      - op: replace
        path: /spec/runStrategy
        value: Always
      # add volumes for secret and configmap
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud
        value: {
          "secretRef": {
            "name": "cloudinitdisk-client"
          }
        }
      - op: add
        path: /spec/template/spec/volumes/-
        value: {
          "name": "sssd-conf",
          "configMap": {
            "name": "sssd-conf"
          }
        }
      - op: add
        path: /spec/template/spec/domain/devices/disks/-
        value: {
          "name": "sssd-conf",
          "serial": "sssd-conf",
          "disk": {
            "bus": "virtio"
          }
        }