apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-hostpath-volume

labels:
  - includeSelectors: true
    pairs:
      demo: hostpath-volume

components:
  - ../components/automount-role/

resources:
  - namespace.yaml
  - deployment.yaml
