# This is a base image for the automount daemonset
FROM registry.redhat.io/ubi9/ubi:latest

LABEL name="automount"
LABEL description="This image is used to run the automount daemonset on a OpenShift cluster"
LABEL maintainer="dbewley@redhat.com"
LABEL instructions="Build on a RHEL 9 node to enable Red Hat dnf repo access"
LABEL source="https://github.com/dbewley/demo-autofs"
LABEL repo="https://quay.io/repository/dbewley/autofs"

# These RPMs are already installed on a OCP 4.18 node:
#   - nfs-utils-2.5.4-26.el9_4.1.x86_64
#   - openldap-2.6.6-3.el9.x86_64
#   - sssd-2.9.4-6.el9_4.3.x86_64
#   - sssd-ldap-2.9.4-6.el9_4.3.x86_64
#   - sssd-client-2.9.4-6.el9_4.3.x86_64

RUN dnf install \
        --disablerepo=* \
        --enablerepo=rhel-9-for-x86_64-baseos-rpms \
        -y \
        autofs \
        openldap-clients \
        sssd-client \
        strace \
        && dnf clean all

ENTRYPOINT [ "automount" ]
CMD [ "--force", "--foreground", "--timeout", "0", "--dont-check-daemon", "--debug" ]