apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: automount
spec:
  selector:
    matchLabels:
      app: automount
  template:
    metadata:
      labels:
        app: automount
    spec:
      # only run on test nodes
      nodeSelector:
        demo: automount
      serviceAccountName: automount
      hostPID: true
      hostNetwork: true
      containers:
        - name: automount
          image: quay.io/dbewley/autofs:v4.18
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
            - automount
            - --force
            - --foreground
            - --timeout
            - "0"
            - --dont-check-daemon
            - --debug
            - --verbose
          volumeMounts:
            - name: sssd-conf
              mountPath: /etc/sssd/sssd.conf
              subPath: sssd.conf
            - name: lib-sssd
              mountPath: /var/lib/sss
            # works without this, but sssd-client is installed in the image
            # - name: lib64-sssd
            #   mountPath: /lib64/sssd
            - name: automount-conf
              mountPath: /etc/auto.master.d/extra.autofs
              subPath: extra.autofs
            - name: automount-conf
              mountPath: /etc/auto.home
              subPath: auto.home
            - name: var-cache
              mountPath: /var/cache
            - name: home
              mountPath: /home
              # Bidirectional mount propagation is required
              mountPropagation: Bidirectional
            - name: mnt
              mountPath: /mnt
              # Bidirectional mount propagation is required
              mountPropagation: Bidirectional

      volumes:
        # nsswitch.conf already looks ok. must we mount it though?
        - name: lib-sssd
          hostPath:
            path: /var/lib/sss
        # # openat(AT_FDCWD, "/lib64/glibc-hwcaps/x86-64-v3/libnss_sss.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
        # - name: lib64-sssd
        #   hostPath:
        #     path: /lib64/sssd

        - name: var-cache
          hostPath:
            path: /var/cache

        - name: sssd-conf
          configMap:
            name: sssd-conf

        - name: automount-conf
          configMap:
            name: automount-conf

        - name: mnt
          hostPath:
            path: /var/mnt

        - name: home
          hostPath:
            path: /var/home