apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automount-nfs-poc

images:
  - name: quay.io/noseka1/openshift-toolbox
    # newName: quay.io/noseka1/toolbox-container
    # newTag: basic
    newName: quay.io/dbewley/nfs-utils
    newTag: ldap

configMapGenerator:
- name: automount-run
  files:
  - run.sh
- name: automount-conf
  files:
  - scripts/extra.autofs
  - scripts/extra.nfs
configMapGenerator:
  - name: sssd-conf
    files:
      - scripts/sssd.conf

resources:
- automount-ds.yaml
- automount-sa.yaml
- automount-scc-rolebinding.yaml
- automount-scc-role.yaml
