apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automount-nfs-poc

images:
  - name: quay.io/dbewley/autofs
    newName: quay.io/dbewley/autofs
    newTag: v4.18

configMapGenerator:
  - name: automount-run
    files:
      - run.sh

  - name: automount-conf
    files:
      - scripts/extra.autofs
      - scripts/extra.nfs

  - name: sssd-conf
    files:
      - scripts/sssd.conf

resources:
  - automount-ds.yaml
  - automount-sa.yaml
  - automount-scc-rolebinding.yaml
  - automount-scc-role.yaml