---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: argocd-vm-management
rules:
- apiGroups:
  - virtualmachines.kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - '*'