apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    demo: nfs-volume
  name: demo-nfs-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: nfs-volume
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        demo: nfs-volume
    spec:
      serviceAccountName: automount
      containers:
      - image: registry.k8s.io/e2e-test-images/agnhost:2.40
        name: agnhost
        args:
          - test-webserver
          - --port
          - "8080"
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: nfs-home-volume
      volumes:
      - name: nfs-home-volume
        nfs:
          server: nfs.lab.bewley.net
          path: /exports/home/dale
          readOnly: true