apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-nfs-volume

labels:
  - includeSelectors: true
    pairs:
      demo: nfs-volume


resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
