apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeSelector:
    demo: automount
  containers:
  - image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
      - test-webserver
      - --port
      - "8080"
    name: test-container
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    nfs:
      server: nfs.lab.bewley.net
      path: /exports/home/dale
      readOnly: true
