---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../../components/localnet-1924

patches:
  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/devices/interfaces/0
        value: {
          "name": "nic-1924",
          "bridge": {},
          "model": "virtio"
        }
      - op: replace
        path: /spec/template/spec/networks/0
        value: {
          "name": "nic-1924",
          "multus": {
            "networkName": "localnet-1924-dhcp"
          }
        }
