---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - multinetworkpolicy.yaml

components:
  - ../../../components/localnet-1924

patches:
  - target:
      kind: Namespace
      name: .*
    patch: |-
      - op: add
        path: /metadata/labels
        value: { localnet: "1924" }

  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/domain/devices/interfaces/0
        value: {
          "name": "nic-1924",
          "bridge": {},
          "model": "virtio"
        }
      - op: replace
        path: /spec/template/spec/networks/0
        value: {
          "name": "nic-1924",
          "multus": {
            "networkName": "localnet-1924-dhcp"
          }
        }
