---
# https://ovn-kubernetes.io/api-reference/userdefinednetwork-api-spec/#clusteruserdefinednetworkspec
# can only be created by cluster-admin
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: localnet-1924
spec:
  # what namespaces should have access to this network
  namespaceSelector:
    matchLabels:
      labnet: 1924
  network:
    topology: Localnet
    localnet:
      role: Secondary
      # bridge mapping
      physicalNetworkName: physnet-br-vmdata
      vlan:
        mode: Access
        access:
          id: 1924
      subnets:
        - "192.168.4.0/24"
      # do not dole out these IPs
      excludeSubnets:
        - "192.168.4.0/25"
        - "192.168.4.128/26"
        - "192.168.4.240/28"