---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: localnet-1926-dhcp
spec:
  # what namespaces should have access to this network
  namespaceSelector:
    matchLabels:
      vlan-1926: ""
  network:
    topology: Localnet
    localnet:
      role: Secondary
      # bridge mapping
      physicalNetworkName: physnet-br-vmdata
      vlan:
        mode: Access
        access:
          id: 1926
      ipam:
        mode: Disabled

