---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-management
rules:
  - apiGroups:
    - project.openshift.io
    resources:
      - projects
    verbs:
      - '*'
